apiVersion: v1
kind: Service
metadata:
  name: nutritiontracker
  namespace: nutritiontracker
spec:
  selector:
    app: nutritiontracker
  ports:
  -  protocol: TCP
     port: 80
     targetPort: 80
  type: NodePort
